### PR TITLE
fix: add MrKrishnaAgarwal 

### LINKED ISSUE #1174: Krishna Agarwal

### PR DESCRIPTION
**Pull request by MrKrishnaAgarwal**
resolves #1174 

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [x] Changes made in this PR are mentioned below
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.
- [x] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

People will get inspired!

### CODE REVIEW

**Comment by MrKrishnaAgarwal** [comment]
@schmelto 
Please review and approve this one too.

**Comment by Pradumnasaraf** [comment]
> @schmelto Please review and approve this one too.

Hey! Krishna, you don't tag any Maintainers for the review. We get a notification for that, and try our best to review your Pull Request ASAP
Thank you for understanding. :smile:

**Comment by MrKrishnaAgarwal** [comment]
> > @schmelto Please review and approve this one too.
> 
> Hey! Krishna, you don't tag any Maintainers for the review. We get a notification for that, and try our best to review your Pull Request ASAP Thank you for understanding. 😄

Sorry for that
Will remember next time

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge.

**Small suggestion**: If you could use a shorter version of the Screenshot the profile will be more visble.



__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by Pradumnasaraf** [comment]
> > > @schmelto Please review and approve this one too.
> > 
> > 
> > Hey! Krishna, you don't tag any Maintainers for the review. We get a notification for that, and try our best to review your Pull Request ASAP Thank you for understanding. smile
> 
> Sorry for that Will remember next time

NO worries, we all are learning :)

**Review by schmelto — APPROVED** [review]
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
