### PR TITLE
add jatinagg1

### PR DESCRIPTION
**Pull request by jatinagg1**
resolves #issueNumber

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [x] Changes made in this PR are mentioned below
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.
- [x] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please resolve the merge conflicts [**here**](https://github.com/EddieHubCommunity/awesome-github-profiles/pull/1410/conflicts).
Let us know if you need any help with that!

**Comment by jatinagg1** [comment]
How am I supposed to make the required changes?

**Comment by Panquesito7** [comment]
> How am I supposed to make the required changes?

You can copy the content from [`profiles.md`](https://raw.githubusercontent.com/EddieHubCommunity/awesome-github-profiles/main/profiles.md), paste it into the file editor [**here**](https://github.com/EddieHubCommunity/awesome-github-profiles/pull/1410/conflicts), and fix the conflicts.
Eventually, the GitHub Actions workflow will automatically update that file as needed. 🙂

Let us know if you need any help with performing that!

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
It seems you haven't made an issue for your profile yet.
Could you please make an issue with your name and a screenshot of your GitHub profile?

Let us know if you need any help. Thanks. 🙂

**Comment by Pradumnasaraf** [comment]
Closing PR due to inactivity. Feel free to raise a new one.

**Pull request closed without merging**
