### PR TITLE
add fcsouza

### LINKED ISSUE #378: Fabricio Cavalcante
Captura de tela de 2021-02-28 18-52-37

### PR DESCRIPTION
**Pull request by fcsouza**
resolve #378

### CODE REVIEW

**Review by AllanRegush — APPROVED** [review]
Looks Good 👍 Thank you

**Comment by AllanRegush** [comment]
It appears there is a conflict. Could you resolve this?

**Comment by fcsouza** [comment]
> It appears there is a conflict. Could you resolve this?

done :)

**Review by Vyvy-vi — APPROVED** [review]
LGTM-! : )

**Review by Vyvy-vi — APPROVED** [review]

**Comment by AllanRegush** [comment]
Looks like there is another conflict.

**Comment by fcsouza** [comment]
> Looks like there is another conflict.

done.

**Pull request merged**
