### PR TITLE
Create bylickilabs.json

### LINKED ISSUE #1573: [PROFILE ADDITION] <bylickilabs>
### Profile screenshot

image

### PR DESCRIPTION
**Pull request by bylickilabs**
resolves #1573 

## Checklist for profile addition

- [x] Name the PR `fix: add <bylickilabs>`.
- [x] You've added file named `bylickilabs.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [x] Changes made in this PR are mentioned below
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.
- [x] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Comment by bylickilabs** [comment]
I would be very happy, how long will it take to record my profile and make it visible under Profiles? would love to create the corresponding badge! Greetings

**Comment by Panquesito7** [comment]
> I would be very happy, how long will it take to record my profile and make it visible under Profiles? would love to create the corresponding badge! Greetings

Your profile will be shown in the profiles tab once your PR is merged. We usually wait until two or more maintainers approve, then we can proceed to merge the PR. 🙂

**Review by schmelto — APPROVED** [review]
## Looking good to me

Your suggested changes looking good to me.

---
**Summary:** :ok_hand: This code looks good

**Comment by bylickilabs** [comment]
Vielen Dank

**Comment by bylickilabs** [comment]
Screenshot Update uploaded, please fix: bylickilabs
@schmelto @Panquesito7

**Comment by schmelto** [comment]
@Panquesito7 if you want your screenshot to be updated you can submit a new pr for this request.

**Comment by bylickilabs** [comment]
Ok, Danke. Werde es heute Abend einreichen

**Pull request merged**
