### PR TITLE
fix prettier issue

### PR DESCRIPTION
**Pull request by schmelto**

### CODE REVIEW

**Review by Panquesito7 — COMMENTED** [review]
It seems it's not fixed yet. 🤔

**Comment by schmelto** [comment]
Yeah but I don't know why..

**Comment by schmelto** [comment]
I would like to merge this one and leave the other prettier issues to someone else

**Comment by schmelto** [comment]
https://github.com/EddieHubCommunity/awesome-github-profiles/commit/698b86adf92b5f0de38661fc50a1438b9e62e129

Think this resolved the issue

**Pull request merged**
