### PR TITLE
Update data.json

### PR DESCRIPTION
**Pull request by muhammadawaisshaikh**

### CODE REVIEW

**Review by AllanRegush — APPROVED** [review]
Looks Good :+1: Thank you :smile:

**Comment by AllanRegush** [comment]
It looks like is a conflict. Could you fix this? If you need any help let me know :nerd_face:

**Comment by muhammadawaisshaikh** [comment]
@AllanRegush updated.

**Review by AllanRegush — APPROVED** [review]
Looks Good 👍 Thank You 😄

**Pull request merged**
