### PR TITLE
Update data.json

### PR DESCRIPTION
**Pull request by sakshamgurbhele**

### CODE REVIEW

**Review by AllanRegush — APPROVED** [review]
Looks Good :+1: Thank you

**Comment by AllanRegush** [comment]
It looks like there is a conflict. Could you fix this? If you need any help let me know :nerd_face:

**Comment by sakshamgurbhele** [comment]
@AllanRegush HELP! There is something branch issue, How can I fix this?

**Comment by AllanRegush** [comment]
That's fine. Branches with `-` cannot be checked out by the action.

**Comment by AllanRegush** [comment]
@sakshamgurbhele if you need any help let me know :nerd_face:

**Comment by sakshamgurbhele** [comment]
@AllanRegush yes I need help! I am a beginner can you please tell me steps to fix this

**Comment by AllanRegush** [comment]
@sakshamgurbhele What do you need help with? The conflict?

**Comment by sakshamgurbhele** [comment]
@

> @sakshamgurbhele What do you need help with? The conflict?

yes

**Comment by sakshamgurbhele** [comment]
@AllanRegush YES, the conflict

**Comment by AllanRegush** [comment]
@sakshamgurbhele This [link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github) will help you with resolving conflicts.

**Comment by eddiejaoude** [comment]
Looks like the git conflict did not get resolved correctly. It might be easier to close this PR and create a new one?

**Pull request closed without merging**
