### PR TITLE
Update json with Kaiwalya Koparkar profile added

### PR DESCRIPTION
**Pull request by kaiwalyakoparkar**

### CODE REVIEW

**Review by kaiwalyakoparkar — COMMENTED** [review]
Added the name at last :+1:

**Comment by schmelto** [comment]
Look g good the Linter just mark up the branch name maybe we should open another issue about this case it's is not a problem at all when you use branches on your fork (more or less it's best practice) so I think the Linter should not send an error here.



If you want you can open an issue for this one to get some more green squares 🚀

**Review by schmelto — CHANGES_REQUESTED** [review]
@krabhisharma could you resolve the merge conflict? If you need any help let us know 🚀
and could you add "resolve #475" to the description?

thanks again for you support in Discord 😄

**Comment by kaiwalyakoparkar** [comment]
You mentioned wrong person :smile:

**Review by schmelto — APPROVED** [review]
LGTM 🚀

**Comment by kaiwalyakoparkar** [comment]
Thanks, @schmelto :smile:

**Pull request merged**
