### PR TITLE
Favicon added

### LINKED ISSUE #1625: [OTHER] Add a favicon to the website
### Description

We can add a favicon to the website to make it look more stylish.
What icon should we use? I was thinking of EddieHub's mascot. 🤔

### PR DESCRIPTION
**Pull request by Rishav1707**
resolves #1625 

## Other additions/changes

- [x] Changes made in this PR are mentioned below
- [x] I acknowledge that all my contributions will be made under the project's license.
- [x] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes
- Favicon added to the website.

### CODE REVIEW

**Review by Panquesito7 — COMMENTED** [review]
It'd be best to use `favicon.ico` rather than `.png` format, IMO.

**Comment by Rishav1707** [comment]
> It'd be best to use `favicon.ico` rather than `.png` format, IMO.

ok

**Review by Panquesito7 — APPROVED** [review]
Looks good. Thanks! 🎉
Although not sure if we should change it to lower-case (`favicon.ico`). That'd be better, IMO. But it can be kept as-is, it's still good. 🙂

**Comment by Rishav1707** [comment]
> Looks good. Thanks! 🎉 Although not sure if we should change it to lower-case (`favicon.ico`). That'd be better, IMO. But it can be kept as-is, it's still good. 🙂

Thank you😊

**Comment by Pradumnasaraf** [comment]
Hey @Rishav1707. Can you push an empty commit to re-run the failing action?

Steps:

1)
```bash
git commit --allow-empty -m "Empty-Commit"
```
2)

```bash
git push origin <branch name>
```

**Comment by Rishav1707** [comment]
> Hey @Rishav1707. Can you push an empty commit to re-run the failing action?
> 
> Steps:
> 
> 
> ```shell
> git commit --allow-empty -m "Empty-Commit"
> ```
> 
> 
> ```shell
> git push origin <branch name>
> ```

Done @Pradumnasaraf

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Pull request merged**
