### PR TITLE
add Harkirat Singh

### LINKED ISSUE #645: add Harkirat Singh
[https://github.com/harkiratsm](url)

### PR DESCRIPTION
**Pull request by harkiratsm**
Resolve #645

### CODE REVIEW

**Comment by harkiratsm** [comment]
Issue #645

**Review by schmelto — CHANGES_REQUESTED** [review]
Please add yourself at the end of the data.json

**Review by CodingSpecies — APPROVED** [review]
LGTM @schmelto

**Review by schmelto — APPROVED** [review]

**Comment by schmelto** [comment]
Thanks for your contribution 🚀

**Pull request merged**
