### PR TITLE
Create cleverhare.json

### LINKED ISSUE #1762: [PROFILE ADDITION] Soumyajit Brahma
### Profile screenshot

screencapture-github-cleverhare-2023-03-21-20_50_32

### PR DESCRIPTION
**Pull request by cleverhare**
Added all the details on the JSON file

resolves #1762 

## Checklist for a profile addition

- [ ] Name the PR `fix: add Soumyajit Brahma`.
- [ ] You've added file named `soumyajit.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
I believe the filename must match your GitHub username.
Please update accordingly. Any help, let us know. 🙂

**Comment by cleverhare** [comment]
Sure,I will do the changes

**Comment by cleverhare** [comment]
Yup so did the changes

**Comment by cleverhare** [comment]
May I know when this PR will get merged ?

**Comment by Panquesito7** [comment]
> May I know when this PR will get merged ?

Once another maintainer approves it, it'll be merged. 🙂

**Comment by cleverhare** [comment]
Okay Waiting for it

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Pull request merged**
