### PR TITLE
Add Eke Victor

### LINKED ISSUE #471: Eke Victor
Eke-Victor

### PR DESCRIPTION
**Pull request by Evavic44**
Resolve #471

### CODE REVIEW

**Review by schmelto — CHANGES_REQUESTED** [review]
Looking good for me. 🚀 But there a merge conflict is occurred. Can you fix it? If you need any help please let us know

**Comment by Evavic44** [comment]
> Looking good for me. 🚀 But there a merge conflict is occurred. Can you fix it? If you need any help please let us know

@schmelto How can I fix it?

**Comment by schmelto** [comment]
> @schmelto How can I fix it?

Pull the latest changes from this repo to your local one and than it will show xlxou the conflicts. 

If you need more assistance on how to pull the latest changes etc. let us know 🚀

**Comment by Evavic44** [comment]
> > @schmelto How can I fix it?
> 
> Pull the latest changes from this repo to your local one and than it will show you the conflicts.
> 
> If you need more assistance on how to pull the latest changes etc. let us know 🚀

Hello @schmelto, I fixed the conflicts but there are other changes in the README asking me to commit. 
Here take a look 👇🏾 
Annotation 2021-05-06 184453

Question: _Should I commit then both?._

**Comment by schmelto** [comment]
> Question: _Should I commit then both?._ 

No please only the `data.json`

**Comment by Evavic44** [comment]
> > Question: _Should I commit then both?._
> 
> No please only the `data.json`

I can't push without commiting both changes. Or maybe I should let you fix it. A bit confused. 😕

**Comment by schmelto** [comment]
> I can't push without commiting both changes. Or maybe I should let you fix it. A bit confused. 😕 

`git add data.json`

`git status` this should only bring up data.json

`git commit - m "resolve merge conflict" `

`git push `

**Comment by Evavic44** [comment]
> > I can't push without commiting both changes. Or maybe I should let you fix it. A bit confused. 😕
> 
> `git add data.json`
> 
> `git status` this should only bring up data.json
> 
> `git commit - m "resolve merge conflict" `
> 
> `git push `

I think I've done it. 🤔

**Review by schmelto — APPROVED** [review]
Lgtm 🚀

**Pull request merged**
