### PR TITLE
fix: add SparkScratch-P

### LINKED ISSUE #976: SparkScratch-P
## Profile Screenshot

screencapture-github-SparkScratch-P-2022-01-19-11_16_45

### PR DESCRIPTION
**Pull request by SparkScratch-P**
resolves #976 

## Checklist for a profile addition

- [x] Name the PR `fix: add SparkScratch-P`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [x] Changes made in this PR are mentioned below
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.
- [x] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes:

 The theme was not working on the Github Page. So, I edited and activated the Cayman Jekyll theme.

### CODE REVIEW

**Review by schmelto — CHANGES_REQUESTED** [review]
Please do not modify config.yml

**Comment by SparkScratch-P** [comment]
> Please do not modify config.yml

`Congif.yml `has been replaced with default code. Now, it is ready to be merged!

## Thank You

**Review by schmelto — APPROVED** [review]

**Review by krshdev — APPROVED** [review]

**Review by Pradumnasaraf — APPROVED** [review]

**Comment by SparkScratch-P** [comment]
I am happy to be merged. Well, with this edit, may I become a member of the organization? I wanna be one!

**Comment by SparkScratch-P** [comment]
I will surely check out, and basically, it's merged, right? I mean, my profile will be visible on the main eddiehub website?

**Pull request merged**
