### PR TITLE
Added Badges And Link to website To README.md

### PR DESCRIPTION
**Pull request by CodingSpecies**
#653

### CODE REVIEW

**Comment by schmelto** [comment]
image

**Comment by CodingSpecies** [comment]
I tried to make a new branch, to make a new pr, but it didn't work online, and my git bash seems to have issues, so I couldn't use that either. 

This is just an idea, commit (`tried to sort alphabetically`), of me trying to sort the json alphabetically, I will remove it after. I used https://codeshack.io/json-sorter/ to do it, but at the end of the file, it is a bit mixed up. thanks

**Comment by Panquesito7** [comment]
Next time try to use multiple branches to avoid issues. Let me know if you need any help, @CodingSpecies. 🙂

**Comment by CodingSpecies** [comment]
Sorry guys, I managed to fix my git bash, and forked this repo again, so is it ok if I close this and reopen it in a clean pr? I can also make seperate branches, thank you.

**Pull request closed without merging**
