### PR TITLE
New profile added

### PR DESCRIPTION
**Pull request by Vanshikapandey30**

### CODE REVIEW

**Review by CodingSpecies — CHANGES_REQUESTED** [review]
@Vanshikapandey30 for your image url, please can you use the screenshot of your readme:

image

Use this url: https://user-images.githubusercontent.com/70807500/135111984-f6c4f540-949b-451c-8fb3-22d5daa07575.png

Thanks.

**Comment by CodingSpecies** [comment]
Do you need any help @Vanshikapandey30 ? If so, feel free to ask.

**Comment by Vanshikapandey30** [comment]
Hey!
I’m sorry to bother you, I was just trying to learn git/github so this
happened.
I’m sorry again.

Thank you!
Vanshika.

**Comment by CodingSpecies** [comment]
It's ok! All you have to do, is change the image url, with this: https://user-images.githubusercontent.com/70807500/135111984-f6c4f540-949b-451c-8fb3-22d5daa07575.png . Thanks.

**Pull request closed without merging**
