### PR TITLE
fix: add <Ghat0tkach>

### LINKED ISSUE #1693: [Profile-Addition]<Vikram>
# Profile screenshot

image

### PR DESCRIPTION
**Pull request by Ghat0tkach**
resolves #1693 

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Your filename must have `.json` at the end.
In this case, it should be: `Ghat0tkach.json`.

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by priyankarpal — APPROVED** [review]
LGTM 👍🏻 ⚡

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Pull request merged**
