### PR TITLE
fix: add yash-seth

### LINKED ISSUE #1415: Yash Seth
## Profile Screenshot

image

### PR DESCRIPTION
**Pull request by yash-seth**
resolves #1415

## Checklist for profile addition

- [x] Name the PR `fix: add yash-seth`.
- [x] You've added file named `yash-seth.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [x] Changes made in this PR are mentioned below
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.
- [x] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Review by krshkodes — CHANGES_REQUESTED** [review]
Can you try a screenshot that incorporates more of your profile? Like
image

**Comment by yash-seth** [comment]
Thank you for the suggestion. I have made the changes to the PR. Kindly have a look and let me know if any other changes are required.

**Review by krshkodes — APPROVED** [review]

**Comment by yash-seth** [comment]
Kindly add the `hacktoberfest` or `hacktoberfest-accepted` label to the PR. Thanks!

**Comment by krshkodes** [comment]
@yash-seth these PRs aren't eligible for hacktoberfest - you can contribute to our other projects which are eligible but just adding a name to the list or your profile is not a valid contribution to hacktoberfest

**Comment by yash-seth** [comment]
Understood, thanks for clearing that up. I shall look into the other projects.

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Pull request merged**
