### PR TITLE
 fix: add eshan-sharma (resolve EddieHubCommunity#1136)

### LINKED ISSUE #1136: Eshan Sharma
## Profile Screenshot

hjaksdlf

### PR DESCRIPTION
**Pull request by Eshan-Sharma**
resolves #1136 

## Checklist for a profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [x] Changes made in this PR are mentioned below
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.
- [x] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Eshan-Sharma** [comment]
I was having trouble with working on issue #1126, I am new and was working on the main branch. I have created branch `resolve-issue-1136` for issue #1136 and another branch with the name `resolve-issue-1126` to work on removing profiles that don't exist. Hope you understand the reason behind creating multiple PR again and again.

**Comment by eddiejaoude** [comment]
Multiple PRs with specific pieces of work is good 👍 

It looks like this PR contains multiple pieces of work though, it seems to remove a profile and adds a profile?

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Agreeing with **Eddie's** point. Please revert back both of the changes in `profiles.md` & `profiles/AaquibAli.json` and only keep your profile addition changes.

If you need any help, feel free to reach out!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by Eshan-Sharma** [comment]
Yes, I agree, I tried to revert them back but failed. I am using only GitHub right now, using git commands to revert but unable to do so. I cannot see these changes in my local repo - problem might be, I did not successfully clone the repo to local. Please help

**Comment by eddiejaoude** [comment]
If easier for you, you can create new Pull Requests and copy the contents manually over, then close this one - just an idea

**Comment by Eshan-Sharma** [comment]
Okay I will create a new one

**Pull request closed without merging**
