### PR TITLE
fix: add <StarKnightt>

### LINKED ISSUE #1808: [PROFILE ADDITION] <Prasenjit Nayak>
### Profile screenshot

image

### PR DESCRIPTION
**Pull request by StarKnightt**
resolve #1808

resolves #issueNumber

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [x] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Comment by Panquesito7** [comment]
> > Thanks! 🎉
> 
> Review my PR and merge it .

Your pull request will be merged once one or more maintainers approve the PR. 🙂

**Comment by StarKnightt** [comment]
> > > Thanks! 🎉
> > 
> > 
> > Review my PR and merge it .
> 
> Your pull request will be merged once one or more maintainers approve the PR. 🙂

Thank you so much for your assistance. I appreciate it.

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge :tada:.

**Pull request merged**
