### PR TITLE
add nikita-jain-01

### LINKED ISSUE #442: Nikita jain
Screenshot (1571)

### PR DESCRIPTION
**Pull request by nikita-jain-01**
resolve #442

### CODE REVIEW

**Review by schmelto — APPROVED** [review]

**Review by AllanRegush — APPROVED** [review]
Looks Good :+1: Thank you :smile:

**Comment by AllanRegush** [comment]
Thanks for reviewing @schmelto

**Comment by AllanRegush** [comment]
@nikita-jain-01 Looks like there is a merge confilct. Could you resolve this? If you need any help let us know :nerd_face:

**Comment by praveenscience** [comment]
Just get your changes out and pull the latest code, add your changes and then push it. 😁

**Comment by nikita-jain-01** [comment]
> Just get your changes out and pull the latest code, add your changes and then push it. 😁

Thanks 😊

**Comment by nikita-jain-01** [comment]
@AllanRegush Please check it now

**Review by schmelto — APPROVED** [review]

**Pull request merged**
