### PR TITLE
fix: add chiragjh7

### LINKED ISSUE #1725: [PROFILE ADDITION] Chirag Jhariya
### Profile screenshot

Screenshot (14)

### PR DESCRIPTION
**Pull request by chiragjh7**
resolve #1725

### CODE REVIEW

**Review by PiseAtharva — COMMENTED** [review]
Really good profile, something I felt off was how the image was chopped showing half the tweet message from the profile. If that's what you want to go with, I don't wanna bother you 👍

**Review by chiragjh7 — COMMENTED** [review]
Oh Thanks, I fixed the image. Let me know if there is any error. 👍

**Comment by PiseAtharva** [comment]
> Oh Thanks, I fixed the image. Let me know if there is any error. +1

All Good 👍

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Pull request merged**
