### PR TITLE
docs: update email

### LINKED ISSUE #868: DOCS: Code of Conduct New Email
image

### PR DESCRIPTION
**Pull request by avneesh0612**
closes #868

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]

**Comment by avneesh0612** [comment]
what is this error 🤔 
image

**Comment by Panquesito7** [comment]
> what is this error 🤔 image

I think it's a problem with the action itself: trying to find a branch named `patch-1`, which exists, but only in your fork and not in this repository. 🙂

**Comment by avneesh0612** [comment]
Oh okay

**Review by krishguptadev — COMMENTED** [review]
LGTM!

**Pull request merged**
