### PR TITLE
arvind2602

### LINKED ISSUE #1777: [PROFILE ADDITION] arvind2602
### Profile screenshot
Screenshot 2023-03-31 at 1 15 38 PM

### PR DESCRIPTION
**Pull request by arvind2602**
resolves #1777 

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [x] Changes made in this PR are mentioned below
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.
- [x] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by PiseAtharva** [comment]
Hey Arvind, It seems you have started your PR with a blank json file, can you commit your changes and push them again (linking a PR for you to refer from #1776). Also check the boxes given in your PR template as well 😄

**Review by PiseAtharva — CHANGES_REQUESTED** [review]
Hey Arvind, It seems you have started your PR with a blank json file, can you commit your changes and push them again (linking a PR for you to refer from https://github.com/EddieHubCommunity/awesome-github-profiles/pull/1776). Also do check the boxes given in your PR template😄

**Comment by at-the-vr** [comment]
Hey Arvind, just sending a friendly reminder for your PR

**Review by at-the-vr — APPROVED** [review]
seems legit, you also pulled latest changes (good thinking), do give appropriate PR Title from next time though

**Comment by arvind2602** [comment]
done

**Pull request closed without merging**
