### PR TITLE
Update

### PR DESCRIPTION
**Pull request by MercuGmes**
Update de README

### CODE REVIEW

**Comment by schmelto** [comment]
Why you want to merge the GHpages branch into the main branch?

**Comment by MercuGmes** [comment]
> Why you want to merge the GHpages branch into the main branch? 

Bro the truth I don't understand much github and I'm writing randomly xd

**Review by Pradumnasaraf — COMMENTED** [review]
Hey do the changes on the `main` branch. Closing this PR as this will not be merged under any circumstances.

If you need any help, do ping us on the `#help` channel on EddieHub Discord

**Comment by MercuGmes** [comment]
> Hey do the changes on the `main` branch. Closing this PR as this will not be merged under any circumstances.
> 
> If you need any help, do ping us on the `#help` channel on EddieHub Discord

Bro I dont understand github and you xd

**Pull request closed without merging**
