### PR TITLE
add bhagatpratham

### LINKED ISSUE #639: Pratham Bhagat
Capture

### PR DESCRIPTION
**Pull request by bhagatpratham**
resolve #639

### CODE REVIEW

**Review by schmelto — CHANGES_REQUESTED** [review]
Please add yourself at the end of the data.json file

**Comment by bhagatpratham** [comment]
Sorry for that I will do that

**Comment by bhagatpratham** [comment]
Done @schmelto

**Comment by CodingSpecies** [comment]
@schmelto LGTM

**Review by schmelto — APPROVED** [review]
lgtm

**Pull request merged**
