### PR TITLE
Krishnapro

### LINKED ISSUE #702: Krishna Kumar
githubprofile

### PR DESCRIPTION
**Pull request by Krishnapro**
resolve #702

### CODE REVIEW

**Review by AvidCoder101 — APPROVED** [review]
LGTM, @Krishnapro just to let you know, you don't need to close and re-open a new PR for every commit. Thanks (:

**Review by Panquesito7 — APPROVED** [review]
LGTM 🚀 Thank you for your contribution! 😄👍

**Comment by Krishnapro** [comment]
Thanks for merge this pull request, by the way I'm at beginner level so facing some problem.

**Comment by Panquesito7** [comment]
> Thanks for merge this pull request, by the way I'm at beginner level so facing some problem.

That's totally fine 🙂 we were always beginners once. If you need any help, join the [Discord server](http://discord.eddiehub.org) and great members will help you with your doubts.

**Pull request merged**
