### PR TITLE
Update data.json

### PR DESCRIPTION
**Pull request by kumarankm**

### CODE REVIEW

**Review by AllanRegush — APPROVED** [review]
Looks Good :+1: Thank you :smile:

**Comment by AllanRegush** [comment]
It looks like is a conflict. Could you fix this? If you need any help let me know :nerd_face:

**Comment by kumarankm** [comment]
Thank you😄, Yeah I have fixed the conflicts. Now check and make an approval.

**Comment by kumarankm** [comment]
> It looks like is a conflict. Could you fix this? If you need any help let me know 🤓

Yeah, I have fixed the conflicts. Now check and make an approval.

**Comment by kumarankm** [comment]
> Looks Good 👍 Thank you 😄

Thanks😃

**Comment by kumarankm** [comment]
@AllanRegush , I have made changes. Have a look over it

**Comment by kumarankm** [comment]
@eddiejaoude Right over here, @AllanRegush says it shows some conflicts. But it didn't. Review my pull request, Please!

**Comment by AllanRegush** [comment]
@kumarankm Please be patient. A lot of people in opensource are volunteers. They have obligations in life, work, school, family. Please be courteous to your peers.

**Comment by kumarankm** [comment]
@AllanRegush Sorry😥, I didn't mean that. I was contributing to this for the first time, so I got super excited. Thanks for the help😄

**Pull request merged**
