### PR TITLE
add amino19

### LINKED ISSUE #499: aminos 🇮🇳
github-profile

### PR DESCRIPTION
**Pull request by amino19**
resolve #499

### CODE REVIEW

**Review by starlightknown — APPROVED** [review]

**Review by vinzvinci — APPROVED** [review]
LGTM 👍

**Review by schmelto — APPROVED** [review]

**Comment by schmelto** [comment]
Why did the Github Action was not triggered 🤔

**Comment by amino19** [comment]
Really don't have an idea about that! 
I noticed that, half an hour ago; but I thought may be its manually occurs..

Do let me know, if any suggestion for me?

**Comment by schmelto** [comment]
> Really don't have an idea about that! 
> I noticed that, half an hour ago; but I thought may be its manually occurs..
> 
> Do let me know, if any suggestion for me?
> 

I will take a look later

**Comment by schmelto** [comment]
issue is fixed now

**Pull request merged**
