### PR TITLE
Deploy?

### PR DESCRIPTION
**Pull request by nhcarrigan**
@eddiejaoude I don't see any automation on the repo. Can you confirm we don't have a different deployment approach?

### CODE REVIEW

**Comment by eddiejaoude** [comment]
yep it is the `gh-pages` branch 👍

**Comment by krshdev** [comment]
So we have to make regular PRs to deploy? 🤨

**Comment by nhcarrigan** [comment]
We could do that approach too. Ultimately I defer to Eddie on that.

**Comment by krshdev** [comment]
Can't we just write a GH Action that pushes that to the gh-pages branch? Isn't that simpler

**Comment by nhcarrigan** [comment]
There are a lot of different approaches we can take. 🙂

**Comment by krshdev** [comment]
Just putting this in, for further convo, https://github.com/EddieHubCommunity/awesome-github-profiles/issues/985

**Pull request merged**
