### PR TITLE
add victor-cody

### LINKED ISSUE #512: victor ikechukwu
victor-cody

### PR DESCRIPTION
**Pull request by victor-cody**
resolve #512

### CODE REVIEW

**Review by starlightknown — APPROVED** [review]
LGTM

**Review by vinzvinci — APPROVED** [review]
LGTM 👍

**Review by schmelto — APPROVED** [review]
LGTM

**Comment by schmelto** [comment]
Maybe you could resolve the merge conflict. If you need any help let us know :)

**Review by JayantGoel001 — APPROVED** [review]

**Review by schmelto — CHANGES_REQUESTED** [review]
Could you resolve the merge conflict. If you need any help please let us know 🚀

**Comment by Vyvy-vi** [comment]
Hey @victor-cody,
Do you need any help with resolving these merge conflicts?

**Comment by schmelto** [comment]
Hey @victor-cody how is it looking do you need any assistance from us to resolve the merge conflicts?

**Pull request merged**
