### PR TITLE
fix: add Pal-Sandeep

### LINKED ISSUE #1584: [PROFILE ADDITION] Sandeep Pal
### Profile screenshot

Screenshot from 2022-12-24 10-32-32

### PR DESCRIPTION
**Pull request by Pal-Sandeep**
resolves #1584

### CODE REVIEW

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey, 
The image link you provided is not reachable. Please fix that

**Comment by Pal-Sandeep** [comment]
I have updated [image link](https://user-images.githubusercontent.com/26271825/209422265-ec8bd452-b919-4191-9498-35a18402654d.png). Please review

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Pull request merged**
