### PR TITLE
add nayakastha

### LINKED ISSUE #526: Astha Nayak
github profile

### PR DESCRIPTION
**Pull request by nayakastha**
resolve #526

### CODE REVIEW

**Review by kaiwalyakoparkar — APPROVED** [review]
LGTM :rocket:

**Review by starlightknown — APPROVED** [review]
Lgtm

**Review by schmelto — APPROVED** [review]
Lgtm

**Comment by schmelto** [comment]
Thx @starlightknown and @kaiwalyakoparkar for reviewing
Also thanks to @nayakastha for opening the pr awsome profile 🚀

**Comment by eddiejaoude** [comment]
Awesome collaboration 💥

**Pull request merged**
