### PR TITLE
Add hariketsheth to the list

### LINKED ISSUE #728: Add hariketsheth
image
image

### PR DESCRIPTION
**Pull request by hariketsheth**
Resolve #728

### CODE REVIEW

**Review by CodingSpecies — APPROVED** [review]
LGTM, thank you @hariketsheth

**Review by deephunt3r — APPROVED** [review]
LGTM 🚀 Thanks for your contribution 💯

**Review by Panquesito7 — APPROVED** [review]
LGTM 🚀 Thank you for your contribution! 😄👍
Thanks for reviewing @deephunt3r and @CodingSpecies! 🙂

**Comment by hariketsheth** [comment]
Thanks a lot, @Panquesito7 , @deephunt3r , @CodingSpecies 👍🏻

**Pull request merged**
