### PR TITLE
add adityagarde

### LINKED ISSUE #630: Aditya Garde
adityagarde_github

### PR DESCRIPTION
**Pull request by adityagarde**
resolve #630

### CODE REVIEW

**Review by deephunt3r — APPROVED** [review]
LGTM 👍🏻

**Review by schmelto — APPROVED** [review]
Lgtm

**Comment by schmelto** [comment]
Thanks for your contribution 🚀 and thanks @deephunt3r for reviewing

**Comment by schmelto** [comment]
Thanks for your contribution 🚀 and thanks @deephunt3r for reviewing

**Pull request merged**
