### PR TITLE
fix: Prettier issues

### PR DESCRIPTION
**Pull request by Panquesito7**
Things added/changed:

- Fix Prettier issues.

### CODE REVIEW

**Review by nhcarrigan — APPROVED** [review]
Awesome. Thanks for taking care of this.

**Comment by 1G683654** [comment]
Good day! Can you help me with an issue?

**Comment by Panquesito7** [comment]
> Good day! Can you help me with an issue?

Hey. How can we help? 🙂
By the way, creating a [new issue](https://github.com/EddieHubCommunity/awesome-github-profiles/issues/new/choose) for this would be the best option, IMO.

**Comment by 1G683654** [comment]
Hey, Eddie. Thanks for taking the time to check in on me sir.. I'm trying
to locate videos on how to locate the git terminal command box but no luck.
I'm going to continue looking online and will continue to study more about
this Git and GitHub.  I'll need step by step instructions on how to get
started.. I got the HTML down and just can't "Push" it to publish it.. This
is my only issue at this current moment.. "Team" can someone help me by
sending me a video link?  Just not seeing that "Git page" to select...

**Comment by Panquesito7** [comment]
> Hey, Eddie. Thanks for taking the time to check in on me sir.. I'm trying to locate videos on how to locate the git terminal command box but no luck. I'm going to continue looking online and will continue to study more about this Git and GitHub. I'll need step by step instructions on how to get started.. I got the HTML down and just can't "Push" it to publish it.. This is my only issue at this current moment.. "Team" can someone help me by sending me a video link? Just not seeing that "Git page" to select...

I think asking this in the [support](https://github.com/EddieHubCommunity/support) repository would be better,
or in our [Discord community](http://discord.eddiehub.org), which you should definitely join.

P.S.: I'm not Eddie, hehe. 😅

**Comment by 1G683654** [comment]
Ok, I'll check it out. Hehe, Sorry for calling you Eddie..

**Pull request merged**
