### PR TITLE
fix: add KiranAminPanjwani

### LINKED ISSUE #1108: Kiran Panjwani
## Profile Screenshot

image

image

image

### PR DESCRIPTION
**Pull request by KiranAminPanjwani**
resolves #1108

## Checklist for a profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [x] Changes made in this PR are mentioned below
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.
- [x] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

- "KiranAminPanjwani.json" file has been added.

### CODE REVIEW

**Review by vikasganiga05 — APPROVED** [review]
LGTM :+1: Thanks for contributing. Your github profile looks awesome!

**Review by kabir0x23 — APPROVED** [review]
The code looks good ✨

**Review by schmelto — APPROVED** [review]
## Looking good to me

Your suggested changes looking good to me.
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

**Comment by KiranAminPanjwani** [comment]
> LGTM 👍 Thanks for contributing. Your github profile looks awesome!

Nice to gear from you, thank you so much!✨

**Comment by KiranAminPanjwani** [comment]
> The code looks good ✨

Thank you!✨☺️

**Comment by KiranAminPanjwani** [comment]
> ## Looking good to me
> Your suggested changes looking good to me. __ [sema-logo](https://semasoftware.com/gh)  **Summary:** 👌 This code looks good  |  **Tags:** Elegant

Thank you so much!✨🖤

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to me! :rocket: thank you for your contribution.

**Comment by KiranAminPanjwani** [comment]
@Panquesito7 Kindly merge it, thank you.

**Comment by KiranAminPanjwani** [comment]
@Panquesito7 Is there any other change required?

**Comment by KiranAminPanjwani** [comment]
@Panquesito7 requested change has been completed. Kindly review and merge it. Thank you

**Review by Panquesito7 — APPROVED** [review]

**Review by schmelto — APPROVED** [review]
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by KiranAminPanjwani** [comment]
@Panquesito7 @schmelto Kindly merge my PR, Thank you.✨

**Pull request merged**
