### PR TITLE
add sidharth178

### LINKED ISSUE #235: Samriddhi
Samriddhi-98

### PR DESCRIPTION
**Pull request by sidharth178**
resolve #235

### CODE REVIEW

**Comment by sidharth178** [comment]
resolve #235

**Comment by AllanRegush** [comment]
Hi @sidharth178. Thanks for your pull request. Could you revert this change and try again? I noticed that all of the old entries have been deleted. Make sure you add yourself to the bottom. If you need any help let me know :nerd_face:

**Comment by AllanRegush** [comment]
Hi @sidharth178 Just checking in. If you need any help let me know :nerd_face:

**Review by Vyvy-vi — CHANGES_REQUESTED** [review]
It looks like the data was deleted.
Maybe, sync this file with the repo, and then add your details at the bottom.

Do let us know, if you need any help 🤓

**Comment by Panquesito7** [comment]
Hey, @sidharth178! Just checking in: do you need any help with this? If so, let us know! 😄

**Comment by schmelto** [comment]
closing this due to long inactivity. feel free to reopen or create a new pr for this one 🚀

**Pull request closed without merging**
