### PR TITLE
add Ayushparikh-code

### LINKED ISSUE #519: Ayush Parikh
githubprofile

### PR DESCRIPTION
**Pull request by Ayushparikh-code**
resolve #519

### CODE REVIEW

**Review by starlightknown — APPROVED** [review]
LGTM

**Comment by Ayushparikh-code** [comment]
> LGTM

LGTM means ?

**Comment by starlightknown** [comment]
Looks good to me

**Comment by Ayushparikh-code** [comment]
> Looks good to me

Thanks for helping me out in resolving this pull request !

**Comment by starlightknown** [comment]
Anytime :)

**Review by schmelto — APPROVED** [review]
Lgtm

**Comment by schmelto** [comment]
Tha KS @starlightknown for reviewing and collaboration 🚀

**Comment by Ayushparikh-code** [comment]
@schmelto can u tell me how to add emoji to click when someone click on vote !

**Comment by starlightknown** [comment]
Screenshot_2021-05-19-20-31-25-598_com android chrome
By clicking on that smiley icon you can add emojis

**Comment by Ayushparikh-code** [comment]
> Screenshot_2021-05-19-20-31-25-598_com android chrome
> By clicking on that smiley icon you can add emojis

oh got it thanks again for letting me know this

**Comment by schmelto** [comment]
image
you can also take a look at the top left corner

**Pull request merged**
