### PR TITLE
created new file

### PR DESCRIPTION
**Pull request by AVI-SHUKLA1110**
resolves #issueNumber

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Review by yashdev9274 — CHANGES_REQUESTED** [review]
Do make some changes, update the profile image and upload full profile instead of just bio.
Also update the PR name, you can  have a look at PR templates

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey,

Update your profile with the correct issue number. Also full profile screen shot will look better

**Comment by Pradumnasaraf** [comment]
Duplicate of https://github.com/EddieHubCommunity/awesome-github-profiles/pull/1733

**Comment by Pradumnasaraf** [comment]
duplicate of https://github.com/EddieHubCommunity/awesome-github-profiles/pull/1733

**Comment by Pradumnasaraf** [comment]
Duplicate of https://github.com/EddieHubCommunity/awesome-github-profiles/pull/1733

**Pull request closed without merging**
