### PR TITLE
update readme.md

### PR DESCRIPTION
**Pull request by Komal7209**
added profile details to readme.md again

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
The `README.md` file shouldn't be modified directly. You should edit the `data.json` file instead. Please follow the steps [mentioned here](https://github.com/EddieHubCommunity/awesome-github-profiles#how-can-i-add-my-github-profile) to add your profile and update this PR. Thanks.

**Comment by Komal7209** [comment]
> The `README.md` file shouldn't be modified directly. You should edit the `data.json` file instead. Please follow the steps [mentioned here](https://github.com/EddieHubCommunity/awesome-github-profiles#how-can-i-add-my-github-profile) to add your profile and update this PR. Thanks.

I had already updated my data.json file but readme.md was not updated with my profile details

**Comment by Panquesito7** [comment]
> > The `README.md` file shouldn't be modified directly. You should edit the `data.json` file instead. Please follow the steps [mentioned here](https://github.com/EddieHubCommunity/awesome-github-profiles#how-can-i-add-my-github-profile) to add your profile and update this PR. Thanks.
> 
> I had already updated my data.json file but readme.md was not updated with my profile details

Try to do it again, please. As I said above, `README.md` shouldn't be modified directly.

**Comment by schmelto** [comment]
The readme will be updated on pr merge by a github action

**Comment by Komal7209** [comment]
@schmelto My pr has been merged for data.json but readme was not updated with data

**Comment by schmelto** [comment]
fixed in #707

**Comment by schmelto** [comment]
you should now see your profile in the readme

**Pull request closed without merging**
