### PR TITLE
added HariAcidReign

### LINKED ISSUE #425: Hariharan B
img

### PR DESCRIPTION
**Pull request by HariAcidReign**
resolve #425

### CODE REVIEW

**Review by AllanRegush — APPROVED** [review]
Looks Good :+1: Thank you :smile:

**Comment by AllanRegush** [comment]
Looks like there is conflict. Could you resolve this? :nerd_face:

**Comment by HariAcidReign** [comment]
@AllanRegush How about now? 🚀

**Comment by AllanRegush** [comment]
Marged :tada:

**Pull request merged**
