### PR TITLE
chore: `resolves` -> `closes`

### PR DESCRIPTION
**Pull request by Mhassanbughio**
resolves #issueNumber

## Checklist for profile addition

- [ ] Name the PR `fix: add <mhassanbughio>`.
- [ ] You've added file named `mhassanbughio.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [x] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Mhassanbughio** [comment]
Thank you for awesome repo

**Review by schmelto — APPROVED** [review]
lgtm resolves and closes do both the same thing but ig the meaning behind closing is more intuitive.

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge.

**Review by Panquesito7 — COMMENTED** [review]
Thanks! 🎉

**Pull request merged**
