### PR TITLE
fix: add <zul132>

### LINKED ISSUE #1879: [PROFILE ADDITION] <Fathima Zulaikha>
### Profile screenshot

Github_profile

### PR DESCRIPTION
**Pull request by zul132**
closes #1879 

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

### CODE REVIEW

**Review by zul132 — COMMENTED** [review]
I made a mistake. I appended ".png" to the end of the link generated by the copied profile image. In the zul132.json file, image link should be https://github.com/EddieHubCommunity/awesome-github-profiles/assets/98112914/e5c56a68-003f-40ac-9165-3c142b2c106b

**Comment by zul132** [comment]
Can i make another pull request with the correct image link?

**Comment by Panquesito7** [comment]
> Can i make another pull request with the correct image link?

You can update your current branch and the changes will be reflected in this PR. There's no need for another PR. 🙂

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Pull request merged**
