### PR TITLE
Update data.json

### PR DESCRIPTION
**Pull request by roaldnefs**
Updated `data.json` to add my [personal GitHub profile](https://github.com/roaldnefs) readme (#315).

### CODE REVIEW

**Review by schmelto — APPROVED** [review]
LGTM

**Review by AllanRegush — APPROVED** [review]
Looks Good :+1: Thank you :smile:

**Comment by AllanRegush** [comment]
It looks like there is a conflict. Could you resolve this? If you need any help let me know :nerd_face:

**Comment by AllanRegush** [comment]
Thank you for reviewing @schmelto

**Comment by roaldnefs** [comment]
@AllanRegush, I've resolved the conflict but made sure to not add me as the last profile in the **data.json** file, otherwise we would keep running into conflicts while other PRs are merged first.

**Review by AllanRegush — APPROVED** [review]
Looks Good :+1:

**Comment by eddiejaoude** [comment]
Great work, thanks all 👍

**Pull request merged**
