### PR TITLE
fix: add alokVerma749

### LINKED ISSUE #1120: Alok Kumar Verma
## Profile Screenshot

alokVerma749-Alok-Kumar-verma-·-GitHub

### PR DESCRIPTION
**Pull request by alokVerma749**
#1120 links this PR to the first Issue

resolves #1120

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [x] Changes made in this PR are mentioned below
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.
- [x] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Review by schmelto — APPROVED** [review]
## Looking good to me

Your suggested changes looking good to me.
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

**Review by Panquesito7 — COMMENTED** [review]
Hmm, you actually wrote `alokVerna`. Is that a bug or wanna keep it as-is?

**Comment by alokVerma749** [comment]
> Hmm, you actually wrote `alokVerna`. Is that a bug or wanna keep it as-is?

My username is alokVerma749

**Review by kabir0x23 — CHANGES_REQUESTED** [review]
your .json file is having wrong username
```diff
- alokVerna749.json # Verna contains -> n <- instead of m
+ alokVerma749.json
```
image

**Review by vikasganiga05 — APPROVED** [review]
LGTM :+1: My suggestion is to rename `alokVerna749.json` to `alokVerma749.json` .

**Comment by alokVerma749** [comment]
I renamed it

**Review by Panquesito7 — APPROVED** [review]

**Pull request merged**
