### PR TITLE
add MadhuSaini22

### LINKED ISSUE #1266: Madhu- Saini
profileeeee

### PR DESCRIPTION
**Pull request by MadhuSaini22**
resolves #1266 

## Checklist for profile addition

- [Y] Name the PR `fix: add MadhuSaini22`.
- [Y] You've added file named `MadhuSaini22` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [Y] You've linked the PR to the correct issue.

---

## Other additions/changes

- [Y] Changes made in this PR are mentioned below
- [Y] Search previous suggestions before making a new one, as yours may be a duplicate.
- [Y] I acknowledge that all my contributions will be made under the project's license.
- [Y] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by MadhuSaini22** [comment]
@Panquesito7 I don't know why the Prettier Linking is failing to check, could you help?

**Review by kaiwalyakoparkar — CHANGES_REQUESTED** [review]
The prettier follows 2 space format and I see you have used 4 space indentation format. Could you please change that. Let us know if you need any help :)

**Comment by MadhuSaini22** [comment]
> The prettier follows 2 space format and I see you have used 4 space indentation format. Could you please change that. Let us know if you need any help :)

Sure, I'll format it
Thank You!!

**Comment by MadhuSaini22** [comment]
@kaiwalyakoparkar Done, Please accept the changes :)

**Review by Panquesito7 — APPROVED** [review]
Thanks for contributing! 🚀


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Efficient

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Reusable

**Pull request merged**
