### PR TITLE
fix: update imlakshay08.json

### LINKED ISSUE #1344: Lakshay Tyagi
## Profile Screenshot

Screenshot from 2022-08-30 16-12-39

### PR DESCRIPTION
**Pull request by imlakshay08**
resolves #1344 

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [x] Changes made in this PR are mentioned below
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.
- [x] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Review by Pradumnasaraf — COMMENTED** [review]
Hey, you have 2 PRs open and another one resolve the merge conflict

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by imlakshay08** [comment]
> Hey, you have 2 PRs open, close another one and resolve the merge conflict in this one!
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** hammer_and_wrench This code needs a fix  |  **Tags:** Not reusable

I closed other one but not able to resolve this one

**Comment by Pradumnasaraf** [comment]
> > Hey, you have 2 PRs open, close another one and resolve the merge conflict in this one!
> > __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  
> 
> I have closed the other one but not able to resolve this one.

No worries did it for you, It was slight complicated.

**Comment by Pradumnasaraf** [comment]
Did it for you, so you are updating your profile, instead of adding it, correct?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by imlakshay08** [comment]
> Did it for you, so you are updating your profile, instead of adding it, correct?
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** question I have a question

Yes.

**Review by Panquesito7 — APPROVED** [review]
Looks good. Thanks! 🎉


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contributions :tada:

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome

**Pull request merged**
