### PR TITLE
fix: add SohamRatnaparkhi 

### LINKED ISSUE #1117: Soham Ratnaparkhi
## Profile Screenshot
image
image

### PR DESCRIPTION
**Pull request by SohamRatnaparkhi**
resolve #1117 

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## This PR adds/fixes
This PR involves the addition of my profile to `awesome profiles`.

### CODE REVIEW

**Comment by SohamRatnaparkhi** [comment]
Hi Devs, 
`Prettier / Prettier Linting` check failed for this PR so, how can I pass the check.
Thank you!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Review by vikasganiga05 — APPROVED** [review]
Thanks for contributing! Looks good to me.

**Comment by TAKANOME-DEV** [comment]
Add an end line. I had encountered the same problem.
```diff
- }                                                                                                                                                                                                                         
+ }                                                                                                                                                                                                              
+                                                                                                                                                                                                                    
```

**Comment by SohamRatnaparkhi** [comment]
> Add an end line. I had encountered the same problem.
> 
> ```diff
> - }                                                                                                                                                                                                                         
> + }                                                                                                                                                                                                              
> +                                                                                                                                                                                                                    
> ```

Thank you! I made committed the changes in my latest commit. 
I am new to open-source. Can you tell me what should I do after adding the line and making a commit? Do I have to make new PR or anything of that sort?
Thank you!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by SohamRatnaparkhi** [comment]
> Thanks for contributing! Looks good to me.

Thank you!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by TAKANOME-DEV** [comment]
No, everything looks good. 
Wait for  a member to review it and merge it.

**Comment by SohamRatnaparkhi** [comment]
> No, everything looks good. Wait for a member to review it and merge it.

Great, Thank you!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by SohamRatnaparkhi** [comment]
Hello Devs, any update on this PR? 
Thank you!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Review by vikasganiga05 — APPROVED** [review]
The code looks good to me. But I don't know why there is a linting error in gh-action.

**Comment by schmelto** [comment]
@Panquesito7 maybe you can help here

**Comment by SohamRatnaparkhi** [comment]
Hello Devs, 
Can you help me in removing the linting error?
Thankyou!



__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by TAKANOME-DEV** [comment]
You can go a head and fetch the latest changes from upstream/main and merge them. After that, commit on this branch and it should go away.
Here is an example on how to update fork. [Check it out](https://www.nhcarrigan.com/notes/#/git-commands/update-fork)

**Comment by SohamRatnaparkhi** [comment]
> You can go a head and fetch the latest changes from upstream/main and merge them. After that, commit on this branch and it should go away. Here is an example on how to update fork. [Check it out](https://www.nhcarrigan.com/notes/#/git-commands/update-fork)

Okay thankyou👍

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
