### PR TITLE
Update data.json

### PR DESCRIPTION
**Pull request by kumarankm**

### CODE REVIEW

**Review by schmelto — APPROVED** [review]

**Review by kumarankm — COMMENTED** [review]
Add me, Facing error🐛

**Comment by eddiejaoude** [comment]
@kumarankm did you mean to close this PR?

**Comment by kumarankm** [comment]
@eddiejaoude Yes, I have created another one. But still, it didn't get approved

**Comment by eddiejaoude** [comment]
ok cool 👍 . It will get reviewed soon 🤓

**Pull request closed without merging**
